# Generated by Django 3.2.6 on 2021-10-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211011_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapUserWithRoom',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
