# Generated by Django 3.2.6 on 2021-10-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mapuserwithroom_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mapuserwithroom')),
            ],
        ),
    ]
