# Generated by Django 3.2.6 on 2021-10-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mapped',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomid',
            field=models.IntegerField(null=True),
        ),
    ]
