# Generated by Django 3.2.6 on 2021-10-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211016_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
