# Generated by Django 3.2.6 on 2021-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profilenick_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilenick',
            name='color',
            field=models.CharField(choices=[('#044187', '#044187'), ('#000000', '#000000'), ('#026333', '#026333'), ('#512DA8', '#512DA8')], default='blue', max_length=20),
        ),
    ]
